server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/1909a?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 144
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  application:
     name: service-provider
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka
  instance:
    lease-renewal-interval-in-seconds: 10  #向注册中心发送心跳的频率
    lease-expiration-duration-in-seconds: 30  #若注册中心检测到某个微服务在30秒内未发现心跳，则剔出集群